@startuml
entity users {
  +user_id : INT [PK]
  --
  user_name : VARCHAR(100)
  mail_address : VARCHAR(100)
}

entity channels {
  +channel_id : INT [PK]
  --
  channel_name : VARCHAR(100)
}
entity programs {
  +program_id : INT [PK]
  --
  genre_id : [FK]
  program_name : VARCHAR(100)
  air_time : INT
  season : INT
  episode : INT
  episode_title : VARCHAR(100)
  episode_detail : VARCHAR(100)
  release_date : DATE
  view : INT
}
entity genres {
  +genre_id : INT [PK]
  --
  genre_name : VARCHAR(100)
}

entity slots {
  +slot_id : INT [PK]
  --
  channel_id : INT[FK]
  program_id : INT[FK]
  start_time : DATETIME
  end_time : DATETIME
}
entity histories {
  +history_id : INT [PK]
  --
  slot_id : INT[FK]
  user_id : INT[FK]
}

channels ||-u-o{ slots
programs ||-r-o{ slots
programs }o-d-|| genres
users ||-u-o{ histories
slots ||-r-o{ histories
@enduml