@startuml
entity ユーザ {
  +ユーザid : INT [PK]
  --
  名前 : VARCHAR(100)
  アドレス : VARCHAR(100)
}

entity チャンネル {
  +チャンネルid : INT [PK]
  --
  チャンネル名 : VARCHAR(100)

}
entity 番組 {
  +番組id : INT [PK]
  --
  番組名 : VARCHAR(100)
  時間 : INT
  シーズン : VARCHAR(100)
  エピソード : VARCHAR(100)
  エピソードタイトル : VARCHAR(100)
  エピソード詳細 : VARCHAR(100)
  ジャンルid : [FK]
}
entity ジャンル {
  +ジャンルid : INT [PK]
  --
  ジャンル名 : DATE
}

entity 番組枠 {
  +番組枠id : INT [PK]
  --
  チャンネルid : INT[FK]
  番組id : INT[FK]
  開始時刻
  終了時刻
}
entity 視聴履歴 {
  +履歴id : INT [PK]
  --
  番組枠id : INT[FK]
  ユーザid : INT[FK]
}

チャンネル ||-u-o{ 番組枠
番組 ||-r-o{ 番組枠
番組 }o-d-|| ジャンル
ユーザ||-u-o{ 視聴履歴
番組枠||-r-o{ 視聴履歴
@enduml